name: Docker Installer Download

on:
  workflow_dispatch:
  schedule:
    - cron: '00 23 * * *'

permissions:
  contents: write

jobs:
  download_installer:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download installers
      run: |
         curl -o mediawiki-1.35.14.zip "https://releases.wikimedia.org/mediawiki/1.35/mediawiki-1.35.14.zip"
         

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
          name: mediawiki-1.35.14.zip
          path: mediawiki-1.35.14.zip
